name: Build Plugin
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: make dist
      - uses: actions/upload-artifact@v3
        with:
          name: mattermost-plugin-ai.tar.gz
          path: dist/*.tar.gz

